server:
  port: 9090
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employees
    username: postgres
    password: admin
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true